### ISSUE TITLE
Downloading the 0.0.7 release triggers a Windows Defender detection

### ISSUE THREAD

**Issue by JamesDawson** [sirredbeard/wslinternals#8]
For me at least, it reports the following detections:
* Trojan:Win32/Wacatac.B!ml
* Trojan:Win32/Wacatac.H!ml

**Comment by sirredbeard** [comment]
I have submitted all the files to Microsoft to be removed from Defender. 

![image](https://github.com/sirredbeard/wslinternals/assets/33820650/76fc2db0-5049-4832-aff5-6272d31ea474)

**Comment by sirredbeard** [comment]
Microsoft has started approving the files. All the files in 0.0.8 pass WD on Win11 as of update 1.399.487.0. 

![image](https://github.com/sirredbeard/wslinternals/assets/33820650/ef617e93-f2ab-41b0-a5a3-cfb5bb862107)

Closing this issue for now, but will continue to submit new apps and new versions periodically to Microsoft to ensure they don't get picked up by WD.
